name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      # Non-sensitive values can be defined here or overridden at runtime:
      MQTT_BROKER: "192.168.1.15"
      MQTT_PORT: "31883"
      MQTT_TOPIC: "home/automation/camera_capture"
      CAMERAS: "garage,frontdoor"
      CAMERA_URL_GARAGE: "rtsp://username:password@192.168.1.36/stream1"
      CAMERA_URL_FRONTDOOR: "rtsp://username:password@192.168.1.34/stream1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mortyone/rtsp-mqtt-listener:latest
          platforms: linux/arm/v7
